### PR TITLE
purescript 0.12

### PR DESCRIPTION
**Pull request by shmish111**

### CODE REVIEW

**Comment by Proclivis** [comment]
The Travis CI is failing. Can you have a look?

**Comment by shmish111** [comment]
@Proclivis fixed by using /travis file taken from purescript-prelude

**Comment by shmish111** [comment]
once this is merged, would you be able to do a bower release.

**Comment by shmish111** [comment]
Thanks @Proclivis could you do a release now? I need to access this with bower

**Comment by Proclivis** [comment]
Busy weekend. I have to relearn how to release, been quite awhile. I’ll try to look at it tonight.

**Comment by Proclivis** [comment]
David,

After making a new VM, installing, relearning, etc… it is released.

Mike

**Comment by shmish111** [comment]
Awesome thanks!

I wonder if you would consider adding it to purescript package sets? See https://github.com/purescript/package-sets#add-your-package

**Comment by Proclivis** [comment]
I looked at the docs, more learning than I have time for at the moment.

**Pull request merged**
